### ISSUE TITLE
Crashed android release build - redirect URI mismatch

### ISSUE THREAD

**Issue by Maddumage** [stashenergy/react-native-msal#26]
My application worked perfectly when it run on debug mode. But in release build android app crashed and got following error logs. Please help..

`2020-08-04 14:04:43.834 12483-12483/? E/SPPClientService: [PackageInfoChangeReceiver] android.intent.action.PACKAGE_REMOVED
2020-08-04 14:04:43.835 12483-12483/? E/SPPClientService: [PackageInfoChangeReceiver] [handlePkgRemovedEvent] PackageName : com.triviallife.mobile, true, false
2020-08-04 14:04:43.835 12483-12483/? E/SPPClientService: [PackageInfoChangeReceiver] [handlePkgRemovedEvent] Ignore Replacing case
2020-08-04 14:04:43.849 5205-5205/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/com.doorbell.mobile-4MGsndjuS48RsZ-FySr3qw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:241)
        at android.app.LoadedApk.updateApplicationInfo(LoadedApk.java:377)
        at android.app.ActivityThread.handleDispatchPackageBroadcast(ActivityThread.java:5747)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at com.android.server.SystemServer.run(SystemServer.java:809)
        at com.android.server.SystemServer.main(SystemServer.java:630)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:944)
2020-08-04 14:04:43.905 4814-5414/? E/BufferQueueProducer: [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity[12805]#0] disconnect: not connected (req=1)
2020-08-04 14:04:43.944 5205-14233/? E/WindowManager: win=Window{12e19d9 u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2797 com.android.server.wm.WindowManagerService.relayoutWindow:2494 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack> 
2020-08-04 14:04:44.159 4688-4688/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-04 14:04:44.160 4688-4688/? E/Zygote: accessInfo : 1
2020-08-04 14:04:44.161 4619-4666/? E/unknown:DisabledDevSupportManager: Caught exception
    com.microsoft.identity.client.exception.MsalClientException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.verifyRedirectUriWithAppSignature(PublicClientApplicationConfiguration.java:501)
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:549)
        at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:984)
        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:966)
        at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:72)
        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:866)
        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:852)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:188)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2020-08-04 14:04:44.162 4619-4666/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.triviallife.mobile, PID: 4619`

Do I need to register two different client applications on Azure portal for development and release builds? Please guide me.

**Comment by josmithua** [comment]
It's because when you build for release it uses your production keystore which has a different hash than your debug one.

**Comment by Maddumage** [comment]
@josmithua I generated hash for the production Keystore and updated both server and client-side. But I got this error still.

**Comment by josmithua** [comment]
What are the steps you are taking to create a release build? I will try to reproduce in the example app that is in this repo.

**Comment by Maddumage** [comment]
HI, I found a solution from here https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/931#issuecomment-648186356. 
Thank you!
